// ExportConstants.cpp : Выводит код класса java, содержащий список необходимых констант
//

#include "stdafx.h"

#include <sapi.h>

#include <iostream>
using namespace std;

int _tmain(int argc, _TCHAR* argv[])
{
	wcout <<
			  L"package org.luwrain.windows.speech;"
		L"\n"
		L"\n" L"class  SAPIImpl_constants"
		L"\n" L"{"
		L"\n" L"	// link to documentation https://msdn.microsoft.com/en-us/library/ee431843%28v=vs.85%29.aspx"
		L"\n" L"	public static final int SPF_DEFAULT = " << SPF_DEFAULT << L";"
		L"\n" L"	public static final int SPF_IS_XML = " << SPF_IS_XML << L";"
		L"\n" L"	public static final int SPF_IS_NOT_XML = " << SPF_IS_NOT_XML << L";"
		L"\n" L"	public static final int SPF_ASYNC = " << SPF_ASYNC << L";"
		L"\n" L"	public static final int SPF_PURGEBEFORESPEAK = " << SPF_PURGEBEFORESPEAK << L";"
		L"\n" L"	public static final int SPF_IS_FILENAME = " << SPF_IS_FILENAME << L";"
		L"\n" L"	public static final int SPF_NLP_SPEAK_PUNC = " << SPF_NLP_SPEAK_PUNC << L";"
		L"\n" L"	public static final int SPF_PARSE_SAPI = " << SPF_PARSE_SAPI << L";"
		L"\n" L"	public static final int SPF_PARSE_SSML = " << SPF_PARSE_SSML << L";"
//		L"\n" L"	public static final int  = " << << L";"
L"\n" L"	public static final int SPSF_Default = " << SPSF_Default << L";"
L"\n" L"	public static final int SPSF_NoAssignedFormat = " << SPSF_NoAssignedFormat << L";"
L"\n" L"	public static final int SPSF_Text = " << SPSF_Text << L";"
L"\n" L"	public static final int SPSF_NonStandardFormat = " << SPSF_NonStandardFormat << L";"
L"\n" L"	public static final int SPSF_ExtendedAudioFormat = " << SPSF_ExtendedAudioFormat << L";"
L"\n" L"	public static final int SPSF_8kHz8BitMono = " << SPSF_8kHz8BitMono << L";"
L"\n" L"	public static final int SPSF_8kHz8BitStereo = " << SPSF_8kHz8BitStereo << L";"
L"\n" L"	public static final int SPSF_8kHz16BitMono = " << SPSF_8kHz16BitMono << L";"
L"\n" L"	public static final int SPSF_8kHz16BitStereo = " << SPSF_8kHz16BitStereo << L";"
L"\n" L"	public static final int SPSF_11kHz8BitMono = " << SPSF_11kHz8BitMono << L";"
L"\n" L"	public static final int SPSF_11kHz8BitStereo = " << SPSF_11kHz8BitStereo << L";"
L"\n" L"	public static final int SPSF_11kHz16BitMono = " << SPSF_11kHz16BitMono << L";"
L"\n" L"	public static final int SPSF_11kHz16BitStereo = " << SPSF_11kHz16BitStereo << L";"
L"\n" L"	public static final int SPSF_12kHz8BitMono = " << SPSF_12kHz8BitMono << L";"
L"\n" L"	public static final int SPSF_12kHz8BitStereo = " << SPSF_12kHz8BitStereo << L";"
L"\n" L"	public static final int SPSF_12kHz16BitMono = " << SPSF_12kHz16BitMono << L";"
L"\n" L"	public static final int SPSF_12kHz16BitStereo = " << SPSF_12kHz16BitStereo << L";"
L"\n" L"	public static final int SPSF_16kHz8BitMono = " << SPSF_16kHz8BitMono << L";"
L"\n" L"	public static final int SPSF_16kHz8BitStereo = " << SPSF_16kHz8BitStereo << L";"
L"\n" L"	public static final int SPSF_16kHz16BitMono = " << SPSF_16kHz16BitMono << L";"
L"\n" L"	public static final int SPSF_16kHz16BitStereo = " << SPSF_16kHz16BitStereo << L";"
L"\n" L"	public static final int SPSF_22kHz8BitMono = " << SPSF_22kHz8BitMono << L";"
L"\n" L"	public static final int SPSF_22kHz8BitStereo = " << SPSF_22kHz8BitStereo << L";"
L"\n" L"	public static final int SPSF_22kHz16BitMono = " << SPSF_22kHz16BitMono << L";"
L"\n" L"	public static final int SPSF_22kHz16BitStereo = " << SPSF_22kHz16BitStereo << L";"
L"\n" L"	public static final int SPSF_24kHz8BitMono = " << SPSF_24kHz8BitMono << L";"
L"\n" L"	public static final int SPSF_24kHz8BitStereo = " << SPSF_24kHz8BitStereo << L";"
L"\n" L"	public static final int SPSF_24kHz16BitMono = " << SPSF_24kHz16BitMono << L";"
L"\n" L"	public static final int SPSF_24kHz16BitStereo = " << SPSF_24kHz16BitStereo << L";"
L"\n" L"	public static final int SPSF_32kHz8BitMono = " << SPSF_32kHz8BitMono << L";"
L"\n" L"	public static final int SPSF_32kHz8BitStereo = " << SPSF_32kHz8BitStereo << L";"
L"\n" L"	public static final int SPSF_32kHz16BitMono = " << SPSF_32kHz16BitMono << L";"
L"\n" L"	public static final int SPSF_32kHz16BitStereo = " << SPSF_32kHz16BitStereo << L";"
L"\n" L"	public static final int SPSF_44kHz8BitMono = " << SPSF_44kHz8BitMono << L";"
L"\n" L"	public static final int SPSF_44kHz8BitStereo = " << SPSF_44kHz8BitStereo << L";"
L"\n" L"	public static final int SPSF_44kHz16BitMono = " << SPSF_44kHz16BitMono << L";"
L"\n" L"	public static final int SPSF_44kHz16BitStereo = " << SPSF_44kHz16BitStereo << L";"
L"\n" L"	public static final int SPSF_48kHz8BitMono = " << SPSF_48kHz8BitMono << L";"
L"\n" L"	public static final int SPSF_48kHz8BitStereo = " << SPSF_48kHz8BitStereo << L";"
L"\n" L"	public static final int SPSF_48kHz16BitMono = " << SPSF_48kHz16BitMono << L";"
L"\n" L"	public static final int SPSF_48kHz16BitStereo = " << SPSF_48kHz16BitStereo << L";"
L"\n" L"	public static final int SPSF_TrueSpeech_8kHz1BitMono = " << SPSF_TrueSpeech_8kHz1BitMono << L";"
L"\n" L"	public static final int SPSF_CCITT_ALaw_8kHzMono = " << SPSF_CCITT_ALaw_8kHzMono << L";"
L"\n" L"	public static final int SPSF_CCITT_ALaw_8kHzStereo = " << SPSF_CCITT_ALaw_8kHzStereo << L";"
L"\n" L"	public static final int SPSF_CCITT_ALaw_11kHzMono = " << SPSF_CCITT_ALaw_11kHzMono << L";"
L"\n" L"	public static final int SPSF_CCITT_ALaw_11kHzStereo = " << SPSF_CCITT_ALaw_11kHzStereo << L";"
L"\n" L"	public static final int SPSF_CCITT_ALaw_22kHzMono = " << SPSF_CCITT_ALaw_22kHzMono << L";"
L"\n" L"	public static final int SPSF_CCITT_ALaw_22kHzStereo = " << SPSF_CCITT_ALaw_22kHzStereo << L";"
L"\n" L"	public static final int SPSF_CCITT_ALaw_44kHzMono = " << SPSF_CCITT_ALaw_44kHzMono << L";"
L"\n" L"	public static final int SPSF_CCITT_ALaw_44kHzStereo = " << SPSF_CCITT_ALaw_44kHzStereo << L";"
L"\n" L"	public static final int SPSF_CCITT_uLaw_8kHzMono = " << SPSF_CCITT_uLaw_8kHzMono << L";"
L"\n" L"	public static final int SPSF_CCITT_uLaw_8kHzStereo = " << SPSF_CCITT_uLaw_8kHzStereo << L";"
L"\n" L"	public static final int SPSF_CCITT_uLaw_11kHzMono = " << SPSF_CCITT_uLaw_11kHzMono << L";"
L"\n" L"	public static final int SPSF_CCITT_uLaw_11kHzStereo = " << SPSF_CCITT_uLaw_11kHzStereo << L";"
L"\n" L"	public static final int SPSF_CCITT_uLaw_22kHzMono = " << SPSF_CCITT_uLaw_22kHzMono << L";"
L"\n" L"	public static final int SPSF_CCITT_uLaw_22kHzStereo = " << SPSF_CCITT_uLaw_22kHzStereo << L";"
L"\n" L"	public static final int SPSF_CCITT_uLaw_44kHzMono = " << SPSF_CCITT_uLaw_44kHzMono << L";"
L"\n" L"	public static final int SPSF_CCITT_uLaw_44kHzStereo = " << SPSF_CCITT_uLaw_44kHzStereo << L";"
L"\n" L"	public static final int SPSF_ADPCM_8kHzMono = " << SPSF_ADPCM_8kHzMono << L";"
L"\n" L"	public static final int SPSF_ADPCM_8kHzStereo = " << SPSF_ADPCM_8kHzStereo << L";"
L"\n" L"	public static final int SPSF_ADPCM_11kHzMono = " << SPSF_ADPCM_11kHzMono << L";"
L"\n" L"	public static final int SPSF_ADPCM_11kHzStereo = " << SPSF_ADPCM_11kHzStereo << L";"
L"\n" L"	public static final int SPSF_ADPCM_22kHzMono = " << SPSF_ADPCM_22kHzMono << L";"
L"\n" L"	public static final int SPSF_ADPCM_22kHzStereo = " << SPSF_ADPCM_22kHzStereo << L";"
L"\n" L"	public static final int SPSF_ADPCM_44kHzMono = " << SPSF_ADPCM_44kHzMono << L";"
L"\n" L"	public static final int SPSF_ADPCM_44kHzStereo = " << SPSF_ADPCM_44kHzStereo << L";"
L"\n" L"	public static final int SPSF_GSM610_8kHzMono = " << SPSF_GSM610_8kHzMono << L";"
L"\n" L"	public static final int SPSF_GSM610_11kHzMono = " << SPSF_GSM610_11kHzMono << L";"
L"\n" L"	public static final int SPSF_GSM610_22kHzMono = " << SPSF_GSM610_22kHzMono << L";"
L"\n" L"	public static final int SPSF_GSM610_44kHzMono = " << SPSF_GSM610_44kHzMono << L";"
L"\n" L"	public static final int SPSF_NUM_FORMATS = " << SPSF_NUM_FORMATS << L";"

		L"\n" L"}"
		L"\n";
	return 0;
}

